/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.14.0
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

export const options = {
  //number of virtual users
  vus: 1000,
  //duration of the test
  duration: '10s',
};

const BASE_URL = "http://localhost:8080";
// Sleep duration between successive requests for each VU, in seconds.
const SLEEP_DURATION = 0.5;

// Define an array of data, where each element represents a unique request body
const requestData = [
    { firstName: "John", lastName: "Doe" },
    { firstName: "Jane", lastName: "Smith" },
    { firstName: "Alice", lastName: "Johnson" },
    { firstName: "Bob", lastName: "Williams" },
];

export default function() {
    group("/v0/greetingsFullName", () => {

        // Request No. 1: greetingsFullNameDraft
        {
            // Get the current virtual user's ID
            const vuId = __VU;
            
            // Use the VU ID to get a unique data object from the array
            const dataIndex = (vuId - 1) % requestData.length;
            const currentData = requestData[dataIndex];
            
            let url = BASE_URL + `/v0/greetingsFullName`;
            let params = {
                headers: {
                    "Content-Type": "application/json",
                    "Accept": "*/*"
                }
            };
            let request = http.post(url, JSON.stringify(currentData), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/greeting", () => {
        let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1: greeting
        {
            let url = BASE_URL + `/greeting?name=${name}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/greetingsFullName", () => {

        // Request No. 1: greetingsFullName
        {
            let url = BASE_URL + `/greetingsFullName`;
            // TODO: edit the parameters of the request body.
            let body = {"firstName": "string", "lastName": "string"};
            let params = {
                headers: {
                    "Content-Type": "application/json", "Accept": "*/*"
                }
            };
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });
    sleep(SLEEP_DURATION);
}
