/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.14.0
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

export const options = {
  //number of virtual users
  vus: 10,
  //duration of the test
  duration: '30s',
};

const BASE_URL = "http://localhost:8080";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/v0/greetingsFullName", () => {

        // Request No. 1: greetingsFullNameDraft
        {
            let url = BASE_URL + `/v0/greetingsFullName`;
            // TODO: edit the parameters of the request body.
            let body = {"firstName": "string", "lastName": "string"};
            let params = {
                headers: {
                    "Content-Type": "application/json", "Accept": "*/*"
                }
            };
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/greeting", () => {
        let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1: greeting
        {
            let url = BASE_URL + `/greeting?name=${name}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/greetingsFullName", () => {

        // Request No. 1: greetingsFullName
        {
            let url = BASE_URL + `/greetingsFullName`;
            // TODO: edit the parameters of the request body.
            let body = {"firstName": "string", "lastName": "string"};
            let params = {
                headers: {
                    "Content-Type": "application/json", "Accept": "*/*"
                }
            };
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

}
